# user-service-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
  selector:
    app: user-service

---
# store-service-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001
  selector:
    app: store-service

---
# delivery-service-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  type: NodePort
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30002
  selector:
    app: delivery-service

---
# api-gateway-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
  selector:
    app: api-gateway

---
# mongodb-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30004
  selector:
    app: mongodb

---
# rabbitmq-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
    - name: rabbitmq-port
      port: 5672
      targetPort: 5672
      nodePort: 30005
    - name: rabbitmq-management-port
      port: 15672
      targetPort: 15672
      nodePort: 30006
  selector:
    app: rabbitmq
